/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 18:11:08 GMT 2023
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartBulb_ESTest extends SmartBulb_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1442), (-1442), (double) (-1442), (-1160.5281526516114));
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{ id = -1442 | on = true | installationCost = 0.0, tone=0, dimension=0.0, consumption=0.0}", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = smartBulb0.clone();
      smartBulb0.setConsumption((-3198.7));
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals((-3198.7), smartBulb0.getConsumption(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, (-1283), 0.0, 0.0);
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb0.setDimension((-2834.749313));
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertEquals((-2834.749313), smartBulb0.getDimension(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(245, 1443, 1.0, (-1174.428));
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb0.setTone((-795));
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertEquals((-795), smartBulb0.getTone());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-3315), (-3315), (-3315), (-3315));
      int int0 = smartBulb0.getTone();
      assertEquals(0, int0);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.setTone((-1204));
      int int0 = smartBulb0.getTone();
      assertEquals((-1204), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.getDimension();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1146), (double) (-1146), (-1339.19484887018), (double) (-1146));
      double double0 = smartBulb0.getDimension();
      assertEquals((-1145.9), smartBulb0.dailyConsumption(), 0.01);
      assertEquals((-1339.19484887018), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.getConsumption();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(1903, 1903, 1.0, (double) 1903);
      double double0 = smartBulb0.getConsumption();
      assertEquals(1903.0, double0, 0.01);
      assertEquals(1.0, smartBulb0.getDimension(), 0.01);
      assertEquals(2, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, 0.0, 511.243639, 0.0);
      double double0 = smartBulb0.dailyConsumption();
      assertEquals(0.1, double0, 0.01);
      assertEquals(511.243639, smartBulb0.getDimension(), 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1146), (double) (-1146), (-1339.19484887018), (double) (-1146));
      double double0 = smartBulb0.dailyConsumption();
      assertEquals((-1145.9), double0, 0.01);
      assertEquals((-1339.19484887018), smartBulb0.getDimension(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1442), (-1442), (double) (-1442), (-1160.5281526516114));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
      assertEquals(0.0, smartBulb1.dailyConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(1903, 1903, 1.0, (double) 1903);
      smartBulb0.setTone((-196));
      smartBulb0.clone();
      assertEquals((-196), smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.setInstallationCost(1.0);
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals(1, smartBulb1.getTone());
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(1903, 1903, 1.0, (double) 1903);
      smartBulb0.setOn(true);
      smartBulb0.clone();
      assertEquals(1903.2, smartBulb0.dailyConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1146), (double) (-1146), (-1339.19484887018), (double) (-1146));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals((-1339.19484887018), smartBulb1.getDimension(), 0.01);
      assertEquals((-1145.9), smartBulb1.dailyConsumption(), 0.01);
      assertTrue(smartBulb1.equals((Object)smartBulb0));
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb((SmartBulb) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("SmartDevice", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1146), (double) (-1146), (-1339.19484887018), (double) (-1146));
      double double0 = smartBulb0.getConsumption();
      assertEquals((-1339.19484887018), smartBulb0.getDimension(), 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals((-1146.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1146), (double) (-1146), (-1339.19484887018), (double) (-1146));
      int int0 = smartBulb0.getTone();
      assertEquals((-1339.19484887018), smartBulb0.getDimension(), 0.01);
      assertEquals(1, int0);
      assertEquals((-1146.0), smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(1, 2966.255, 1, 1);
      double double0 = smartBulb0.getDimension();
      assertEquals(1.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals(1.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-1299), (-1299), (-1299), (-1299));
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      
      smartBulb0.setDimension(1);
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, 0, 0, 0);
      SmartBulb smartBulb1 = new SmartBulb(0);
      assertEquals(0.1, smartBulb1.dailyConsumption(), 0.01);
      
      smartBulb1.setTone(0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.0, smartBulb1.dailyConsumption(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, 0, 0, 0);
      boolean boolean0 = smartBulb0.equals(smartBulb0);
      assertTrue(boolean0);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      assertEquals(0.0, smartBulb0.dailyConsumption(), 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, 0, 0, 0);
      SmartBulb smartBulb1 = new SmartBulb(0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.0, smartBulb1.getConsumption(), 0.01);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
      assertFalse(boolean0);
      assertFalse(smartBulb1.equals((Object)smartBulb0));
      assertEquals(0.0, smartBulb0.dailyConsumption(), 0.01);
      assertEquals(0.0, smartBulb1.getDimension(), 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.dailyConsumption();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(0, 0, 0, 0);
      double double0 = smartBulb0.dailyConsumption();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, smartBulb0.getConsumption(), 0.01);
      assertEquals(0.0, smartBulb0.getDimension(), 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(86, 86, 86, 86);
      boolean boolean0 = smartBulb0.equals((Object) null);
      assertEquals(86.2, smartBulb0.dailyConsumption(), 0.01);
      assertEquals(86.0, smartBulb0.getDimension(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertTrue(smartBulb1.equals((Object)smartBulb0));
      
      smartBulb1.setID(2);
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{ id = 0 | on = false | installationCost = 0.0, tone=1, dimension=0.0, consumption=0.0}", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((-14), (-14), (-14), (-14));
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb1.setConsumption(2);
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertEquals(2.0, smartBulb1.getConsumption(), 0.01);
      assertFalse(boolean0);
  }
}
